apiVersion: v1
kind: Service
metadata:
  name: springbootregistrationlogin
  labels:
    app: springbootregistrationlogin
spec:
  type: NodePort
  selector:
    app: springbootregistrationlogin
  ports:
    - protocol: TCP
      port: 8010
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootregistrationlogin
spec:
  selector:
    matchLabels:
      app: springbootregistrationlogin
  replicas: 1
  template:
    metadata:
      labels:
        app: springbootregistrationlogin
    spec:
      containers:
        - name: springbootregistrationlogin
          image: jyotidocker/springbootregistrationlogin:latest
          ports:
            - containerPort: 8010
              livenessProbe:
              httpGet:
                path: /health
                port: 8010
                initialDelaySecond: 30
                timeoutSeconds: 1
